<a href="https://colab.research.google.com/github/ramu11/PyTorch_ML_Models/blob/main/ML_PyTorch/1_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


##Introducion to Tensors
###Creating tensors
Pytorch tensors are created using `torch.tensors`-=https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html


In [ ]:
#scalar
scalar = torch.tensor(8)
scalar

tensor(8)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

8

In [ ]:
# VECTOR
vector = torch.tensor([8, 8])
vector, vector.ndim, vector.shape

(tensor([8, 8]), 1, torch.Size([2]))

In [ ]:
# MATRIX
Matrix = torch.tensor([[8, 8],
                      [9, 9]])

Matrix ,Matrix[0] ,Matrix[1], Matrix.ndim, Matrix.shape

(tensor([[8, 8],
         [9, 9]]),
 tensor([8, 8]),
 tensor([9, 9]),
 2,
 torch.Size([2, 2]))

In [ ]:
# TENSOR
Tensor = torch.tensor([[[1, 2, 3],
                      [2, 3, 4],
                      [3, 4, 5]]])
Tensor, Tensor.ndim, Tensor.shape


(tensor([[[1, 2, 3],
          [2, 3, 4],
          [3, 4, 5]]]),
 3,
 torch.Size([1, 3, 3]))

In [ ]:
Tensor[0]

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [ ]:
# Random Tensors
# Why Random Tensors?

#Random Tensors are important because the way many neural networks learn is that they start with tensors with full of
#random numbersand then adjust those random numbers to better represent the data

#`start with random numbers -> look at data -> update random numbers ->look at data -> update random numbers`
# Torch Random Tensors- https://pytorch.org/docs/stable/generated/torch.rand.html




In [ ]:
# create Random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.ndim


(tensor([[0.5461, 0.4191, 0.3904, 0.5781],
         [0.3608, 0.2098, 0.1461, 0.1759],
         [0.6490, 0.6545, 0.6719, 0.5391]]),
 2)

In [ ]:
random_tensor = torch.rand(1, 3, 4)
random_tensor, random_tensor.ndim

(tensor([[[0.6873, 0.9469, 0.7335, 0.6308],
          [0.8245, 0.8151, 0.0992, 0.6321],
          [0.2086, 0.6663, 0.1922, 0.7657]]]),
 3)

In [ ]:
# Create Random Tensor with similar shape to Image Tensor
random_image_size_tensor  = torch.rand(size=([224,224,3])) # height, with, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [ ]:
1. # Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
1. #Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones.dtype, ones

(torch.float32,
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

### Creating a range of tensors and tensors-like

In [ ]:
1. # Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
1.# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor data types
**Note:** Tensor data types are one of the 3 big errors one run into with pytorch & deep learning :
#1 Tensors not right data type
#2 Tensors not right shape
#3 Tensors not on the right device

In [ ]:
1. # Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # what device is your tensor on
                               requires_grad=False) #

float_32_tensor, float_32_tensor.dtype, float_32_tensor.ndim, float_32_tensor.size()

(tensor([3., 6., 9.]), torch.float32, 1, torch.Size([3]))

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
1. Tenosrs not right data type
2 Tensors not right shape
3 Tensors not on the right device

In [ ]:
1. # Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7624, 0.2562, 0.2740, 0.6424],
        [0.9652, 0.1746, 0.3264, 0.8816],
        [0.5019, 0.0857, 0.4237, 0.0848]])

In [ ]:
# find out details about some_tensor
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.7624, 0.2562, 0.2740, 0.6424],
        [0.9652, 0.1746, 0.3264, 0.8816],
        [0.5019, 0.0857, 0.4237, 0.0848]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Manipulating tensors (tensors operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element wise)
* Division
* Matrix Multiplication


In [ ]:
1 # Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [ ]:
1 # Multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Subtract tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out pytorch in-built functions
torch.mul(tensor, 10)


tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing mltiplication in neural network and deep learning:

1.Element wise multiplication
2.Matrix multiplication (dot product)

More info on Matrix multiplication-https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are 2 main rules that performing matrix multiplication should satisfy:  
1. The **inner dimensions** must match:                                    
#`(3, 2) @ (3, 2)`  won't work
#`(2, 3) @ (3, 2)`  will work
#`(3, 2) @ (2, 3)`  will work

2. The Resulting Matrix has the shape of **outer dimensions**
#(2, 3) @ (3, 2) --> (2, 2)
#(3, 2) @ (2, 3) --> (3, 3)





In [ ]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))


tensor([[0.5107, 0.3897, 0.2415],
        [0.5845, 0.4386, 0.3127],
        [1.1450, 0.8800, 0.5107]])

In [ ]:
#torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print("Equals:", tensor * tensor) # element wise multiplication




tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication
%%time
torch.matmul(tensor, tensor)



CPU times: user 1.05 ms, sys: 7 µs, total: 1.06 ms
Wall time: 1.01 ms


tensor(14)

***one of the most common errors in deep learning: shape errors


In [ ]:
#shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

#torch.matmul(tensor_A, tensor_B) # (this will error)

tensor_A.shape, tensor_B.shape


(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
# To fix the tensor shape issues, one can manipulate the shape of the tensors using **transpose**
# **transpose** switches the axis or dimesnsions of a tensor
tensor_B.T, tensor_B.T.shape

(tensor([[ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([2, 3]))

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]),
 torch.Size([3, 2]))

In [ ]:
# The matrix multiplication works when tensor_B is transposed
print(f"Original shapes:tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes:tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying:tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}<-- Inner dimensions must match")
print("Output:\n")

output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"Output shape: {output.shape}")

Original shapes:tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes:tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying:tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])<-- Inner dimensions must match
Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
Output shape: torch.Size([3, 3])


In [ ]:
### Finding the min, Max, Mean, sum etc (tensor aggregation)

x = torch.arange(0, 100, 10, dtype=torch.float32)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [ ]:
#Find the mean, max, sum torch.mean requires a tensor of float32 data type to work

tensor  = torch.arange(1, 20, 5, dtype=torch.float32)
tensor, torch.mean(tensor), torch.max(tensor), torch.min(tensor), torch.sum(tensor)

(tensor([ 1.,  6., 11., 16.]),
 tensor(8.5000),
 tensor(16.),
 tensor(1.),
 tensor(34.))

### Find the positional min and max

In [ ]:
# Find the position in tensor that has the minimum vale with argmin -> return index position of target tensor where the minimum value occurs
# Find the position in tensor that has the maximum vale with argmax -> return index position of target tensor where the maximum value occurs
x = torch.arange(1, 100, 10, dtype=torch.float32)
x, torch.argmin(x), torch.argmax(x)

(tensor([ 1., 11., 21., 31., 41., 51., 61., 71., 81., 91.]),
 tensor(0),
 tensor(9))

### Reshaping, Stacking, Squeezing and un squeezing tensors
# Reshaping - Reshapes an input tensor to a defined shape
# View - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
# Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
# Squeeze - Removes all `1` dimensions from a tensor
# Unsqueeze - Adds a `1` dimension to a target tensor
# Permute -  Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1.,10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
#x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x (coz a view of a tensor shares the same memory as the original input)
z[:, 0] = 5 # set zeroeth index element to 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x, x], dim=1) # dim=1 using Hstack
x_stacked

tensor([[5., 5., 5., 5., 5.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9.]])

In [ ]:
x_stacked = torch.stack([x, x, x, x, x], dim=0) # dim=0 usig Vstack
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"previous tensor : {x_reshaped}")
print(f"previous tensor : {x_reshaped.shape}")

# remove extra dimension from x_reshaped
x_squeezed = torch.squeeze(x_reshaped)
print(f"new tensor : {x_squeezed}")
print(f"new tensor : {x_squeezed.shape}")




previous tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous tensor : torch.Size([1, 9])
new tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
new tensor : torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"previous tensor : {x_squeezed}")
print(f"previous tensor : {x_squeezed.shape}")

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"new tensor : {x_unsqueezed}")
print(f"new tensor : {x_unsqueezed.shape}")


previous tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous tensor : torch.Size([9])
new tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new tensor : torch.Size([1, 9])


In [ ]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # height, width, color channels

# Permute the original tensor to rearrange the axis
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape:{x_permuted.shape}") # color channels, height, width


Previous shape: torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0] = 2345
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(2345.), tensor(2345.))

In [ ]:
### indexing (selecting data from tensors)
 #Indexing with pyTorch is similar to Numpy


In [ ]:
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new Tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0][0], x[0, 0]


(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
# Let's index on the Most inner bracket (last dimension)
x[0][0][0], x[0, 0, 0], x[0, 0, 1], x[0, 0, 2]
# Display 2nd Row
x[0,1,0], x[0,1,1], x[0,1,2]
# Display 3rd Row
x[0,2,0], x[0,2,1], x[0,2,2]

(tensor(7), tensor(8), tensor(9))

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of 0th but only 1st index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Index on x to return 9
x[0,2,2]

tensor(9)

In [ ]:
# Index on x to return 3,6,9
x[:,:, 2]

tensor([[3, 6, 9]])

In [ ]:
x[:, 0, :], x[:, 1, :], x[:, 2, :]

(tensor([[1, 2, 3]]), tensor([[4, 5, 6]]), tensor([[7, 8, 9]]))

### pyTorch tensors and NumPy
# NumPy is popular scientific python numerical computing library
# PyTorch has functionality to interact with it
# Data in NumPy, want in PyTorch tensor --> torch.from_numpy(ndarray)
# PyTorch tensor --->NumPy ->torch.Tensor.numpy()


In [ ]:
# numPy array to Tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
 # array -> tensor
array, tensor,array.dtype, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 dtype('float64'),
 torch.float64)

In [ ]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [ ]:
# Change the value of array, what this will do to tensor ?
array = array + 1
array, tensor


(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# tensor to NumPy array
tensor = torch.ones(8)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to NumPy ?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility ( trying to take random out of random
# How a neural network learns:
# start with random numbers -> tensor operations -> update random numbers to try to make them better representations of the data (again and again and again)
# To reduce randomness in neural networks and pyTorch comes the concept of a **random seed**
# Essentially what random seed does is **flavour** the randomness
# Extra resources for reproducibility
# https://pytorch.org/docs/stable/notes/randomness.html


In [ ]:
import torch
# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)



tensor([[0.2325, 0.6915, 0.5319, 0.2188],
        [0.6590, 0.0828, 0.8158, 0.3309],
        [0.4249, 0.9899, 0.5738, 0.6300]])
tensor([[0.2568, 0.8146, 0.7678, 0.5944],
        [0.3178, 0.2054, 0.4820, 0.1063],
        [0.5405, 0.6967, 0.4805, 0.0077]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch
# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors on GPUs (and making faster computations)
# GPUs = faster computations on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scene

In [ ]:
# Getting a GPU
!nvidia-smi


Sat Jun 29 09:49:26 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
# check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

### For PyTorch since it's capable of running compute on the GPU or CPU, It's best practise to set up device agonistic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices
  # Ex: Run on GPU if available ,else run on CPU

In [ ]:
# Set up device agonostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count no of devices
torch.cuda.device_count()

1

### Putting tensors and models on the GPU

In [ ]:
# Create a tensor (default on the cpu)
tensor = torch.tensor([1, 2, 3])
# tensor not on GPU
print(tensor, tensor.device)

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU


In [ ]:
# If tensor is on GPU , can't transfer it to NumPy
tensor_on_gpu.numpy() # won't work can't convert cuda:0 device type tensor to numpy

In [ ]:
# To fix the GPU tensor with NumPy issue , we can first set to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])